export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_TASKS_SUCCES = 'FETCH_TASKS_SUCCES'
export const ADD_NEW_TASK = 'ADD_NEW_TASK'
export const UPDATE_TASK_TO_TODO = 'UPDATE_TASK_TO_TODO'
export const REMOVE_ITEM_ON_TASK = 'REMOVE_ITEM_ON_TASK'

export const UPDATE_TODO_TO_ACTIVE = 'UPDATE_TODO_TO_ACTIVE'
export const REMOVE_ITEM_ON_TODO = 'REMOVE_ITEM_ON_TODO'

export const UPDATE_ACTIVE_TO_CLOSED = 'UPDATE_ACTIVE_TO_CLOSED'
export const REMOVE_ITEM_ON_ACTIVE = 'REMOVE_ITEM_ON_ACTIVE'