export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_TASKS_SUCCES = 'FETCH_TASKS_SUCCES'
export const ADD_NEW_TASK = 'ADD_NEW_TASK'
export const UPDATE_TASK_TO_TODO = 'UPDATE_TASK_TO_TODO'
export const REMOVE_ITEM_ON_TASK = 'REMOVE_ITEM_ON_TASK'